name: peforming rust project checkout 

on: [push]

jobs:
  rust-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository 
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml 
      - name: setup the sonarqube 
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        with:
          sonar-token: ${{ secrets.SONAR_QUBE_TOKEN }}
      
