name: Perform Java Project Checkout

on: [push]

jobs:
  java-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          entryPoint: sonar-scanner
          args: |
            -Dsonar.projectKey=java
            -Dsonar.sources=src
            -Dsonar.host.url=https://54.243.1.50:9000
            -Dsonar.login=${{ secrets.SONAR_QUBE_TOKEN }}
          projectBaseDir: .
        env:
          SONAR_HOST_URL: https://54.243.1.50:9000
          SONAR_TOKEN: ${{ secrets.SONAR_QUBE_TOKEN }}